# Generated by Django 3.2.4 on 2021-06-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=40)),
                ('room_code', models.CharField(max_length=3)),
                ('room_number', models.IntegerField(default=0)),
                ('room_capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsearch.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField(default=0)),
                ('departure', models.DateField(default=0)),
                ('guest_number', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gds_number', models.CharField(max_length=32)),
                ('room_number', models.IntegerField(blank=True, default=1)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsearch.contactinfo')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsearch.roomtype')),
            ],
        ),
    ]
