# Generated by Django 3.2.4 on 2021-06-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gds_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
